import Head from 'next/head'
import { useEffect } from 'react'
import { useSelector, TypedUseSelectorHook, useDispatch } from 'react-redux'
import axios from 'axios'
import { AppDispatch } from '../src/store'
import { setUsername, setToken } from '@/features/auth/authSlice'

export default function Home() {
  // const username: TypedUseSelectorHook<any> = useSelector((state: any) =>  state.auth.username);

  const dispatch = useDispatch<AppDispatch>();

  useEffect(() => {
    (
      async() => {
        const username = localStorage.getItem('username');
        const token = localStorage.getItem('token');

        if(username && token){
          dispatch(setUsername(username));
          dispatch(setToken(token));
        } else {
          axios.post('http://localhost:3001/login', {
            email: "asdoiajsd",
            password: "iuahhf"
          })
          .then(res => {
            localStorage.setItem('username', res.data.username);
            dispatch(setUsername("yes"))
          })  
          .catch(err => console.log(err));
          console.log("no");
        }
      }
    )();

    return () => {
      console.log("yes")
    }
  }, [])

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        hello
      </div>
    </>
  )
}
